import Navbar from "@/components/Navbar/Navbar";
import "./globals.scss";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="layout">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
